# Generated by Django 5.0.6 on 2026-07-28 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_role_manager',
            field=models.BooleanField(default=False),
        ),
    ]
