# Generated by Django 5.0.6 on 2026-07-22 00:11

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('institution', models.CharField(blank=True, max_length=255)),
                ('order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ReviewAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('decision', models.CharField(choices=[('pending', 'Pending'), ('accept', 'Accept'), ('minor_revisions', 'Minor revisions'), ('major_revisions', 'Major revisions'), ('reject', 'Reject')], default='pending', max_length=20)),
                ('comments_to_author', models.TextField(blank=True)),
                ('comments_to_editor', models.TextField(blank=True)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('due_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=500)),
                ('abstract', models.TextField()),
                ('keywords', models.JSONField(blank=True, default=list)),
                ('submission_type', models.CharField(choices=[('journal_article', 'Journal article'), ('conference_paper', 'Conference paper'), ('thesis', 'Thesis'), ('dissertation', 'Dissertation'), ('policy_brief', 'Policy brief'), ('working_paper', 'Working paper'), ('book_chapter', 'Book chapter'), ('book', 'Book'), ('dataset', 'Dataset')], max_length=30)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('editorial_screening', 'Editorial screening'), ('peer_review', 'Peer review'), ('revision_requested', 'Revision requested'), ('accepted', 'Accepted'), ('published', 'Published'), ('rejected', 'Rejected')], default='draft', max_length=30)),
                ('research_area', models.CharField(blank=True, max_length=255)),
                ('sdgs', models.JSONField(blank=True, default=list)),
                ('references', models.TextField(blank=True)),
                ('doi', models.CharField(blank=True, max_length=100, null=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SubmissionFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='submissions/%Y/%m/')),
                ('label', models.CharField(default='manuscript', max_length=100)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
