# Generated by Django 5.0.6 on 2026-07-28 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='au_agenda_areas',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
